### ISSUE TITLE
Option to ignore warnings from Gnuplot

### ISSUE THREAD

**Issue by abrock** [dstahlke/gnuplot-iostream#13]
I have a program which generates thousands of plots, some of them have an empty x-range and my program's output gets cluttered with warnings from Gnuplot:

> Warning: empty x range [0:0], adjusting to [-1:1]

Is there a way to have gnuplot-iostream ignore / not print them?

**Comment by dstahlke** [comment]
Sorry for the slow response.  On Linux you can construct the gnuplot-iostream object like this:

    Gnuplot gp("gnuplot 2>/dev/null");

This uses the shell to filter out warnings.  On Windows, I don't know.  It sounds like `"gnuplot  > NUL 2>&1"` might work.

The other option would be to tell gnuplot not to emit warnings.  But it sounds like there is no way to do so: https://stackoverflow.com/questions/50698369/gnuplot-suppress-warning
