### ISSUE TITLE
Adding Support For Eigen Library

### ISSUE THREAD

**Issue by KMacha** [dstahlke/gnuplot-iostream#15]
Hey,
Is it possible to add support for the Eigen library.
I was trying to plot an Eigen matrix and there was a compile error: "Container not deep enough"

**Comment by dstahlke** [comment]
Done.  You can see examples in example-data-1d.cc and example-data-2d.cc.  Please let me know if there are any problems.  I've also implemented a new subplots interface that makes it easy to plot many traces at once.  That's not fully documented anywhere, but the examples should hopefully be self explanatory.
