### ISSUE TITLE
gnuplot used in visual studio 2015

### ISSUE THREAD

**Issue by yunxiaoshan** [dstahlke/gnuplot-iostream#2]
Hi, 
I used it on Qt on linux, everything is good, but when I want to use it in VS, it does not go as I expect.
 I read the instruction of yours. I put the path of gnuplot in the defination of 
`Gnuplot Gp1("\"C:\Program Files\gnuplot\bin\gnuplot.exe\"");`
But I got error from it , 
In the cmd window,  the error is 
`C:program is not command.....`

**Comment by dstahlke** [comment]
Sorry for the delayed response.  Try this:
Gnuplot Gp1("C:\\Program Files\\gnuplot\\bin\\gnuplot.exe");
Or perhaps:
Gnuplot Gp1("\"C:\\Program Files\\gnuplot\\bin\\gnuplot.exe\"");

**Comment by PayasR** [comment]
The problem is the space character. 
See: https://stackoverflow.com/questions/1557091/how-to-call-popen-with-a-pathname-containing-spaces-under-windows-in-c-c
