### ISSUE TITLE
Could NOT find Boost (missing: Boost_INCLUDE_DIR iostreams system   filesystem)

### ISSUE THREAD

**Issue by 20yrwu1** [dstahlke/gnuplot-iostream#24]
hello, when I try to compile the code and input "cmake ./ -G "MinGW Makefiles"", but something wrong happen like following:
-----------------------------------------------------------------------------------------------------------------------------------------------
C:\Users\yrwu\Desktop\porous\gnuplot-iostream-master>cmake ./ -G "MinGW Makefiles"
CMake Error: Error: generator : MinGW Makefiles
Does not match the generator used previously: MSYS Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.

C:\Users\yrwu\Desktop\porous\gnuplot-iostream-master>cmake ./ -G "MinGW Makefiles"
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR iostreams system
  filesystem)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
  CMakeLists.txt:9 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/yrwu/Desktop/porous/gnuplot-iostream-master/CMakeFiles/CMakeOutput.log".

-----------------------------------------------------------------------------------------------------------------------------------------------
please help me, I would very grateful to you.

**Comment by 20yrwu1** [comment]
My computer version is window10, which always happens when I use window10 to compile cmake.

**Comment by dstahlke** [comment]
I think you probably just need to set the environment variable BOOST_ROOT to point to where you have installed boost.  Note that cmake is only needed for building the example scripts.  And if cmake isn't working you can try using the Makefile, but you may need to edit CXXFLAGS and LDFLAGS so the compiler can find your boost installation.
