### ISSUE TITLE
How to plot data in real time in 3D coordinate system？

### ISSUE THREAD

**Issue by KungZell** [dstahlke/gnuplot-iostream#26]
Sorry to bother you again, I want to use gnuplot to draw the vector data of the connection vs c++ in real-time in the 3D coordinate system, can you give an example? Thank you so much!! @dstahlke

**Comment by dstahlke** [comment]
I'm not sure I understand what you are trying to do, but I would suggest you take a look at the examples (example-*.cpp in the repository) to see if any of those are similar to what you want.

**Comment by KungZell** [comment]
In fact, I want to pass the dynamic data generated in visual studio to the library to realize the dynamic display of 3D data. Do you think this is feasible?

**Comment by dstahlke** [comment]
Take a look at demo_animation() in example-misc.cc.  This passes dynamically changing data to gnuplot.  The same can be done for 3D plots.
