### ISSUE TITLE
Please enable HTTPS for documentations on stahlke.org

### ISSUE THREAD

**Issue by jokolaco** [dstahlke/gnuplot-iostream#27]
Hello Dan,

unfortunaletely i cannot access your domain and read the docs because of wrong server configuration.
Even if i disable https it will not work.

Best regards 

NearlyFreeSpeech.NET Logo
stahlke.org: TLS Not Enabled

You have attempted to access this site via TLS (HTTPS), but it is not configured for TLS access.

Please [follow this link](http://stahlke.org/) to visit the site without TLS.
400 Bad Request
[NearlyFreeSpeech.NET](https://www.nearlyfreespeech.net/)

**Comment by dstahlke** [comment]
At the time I setup my page, my host did not support https.  I see they now do, so I may set this up at some point.  However, for now, it should be available via the non-encrypted http link.  What do you get when following the "follow this link to visit the site without TLS" link?
