### ISSUE TITLE
Can you please give an example with a 3D plot in your documentation? 

### ISSUE THREAD

**Issue by infoclogged** [dstahlke/gnuplot-iostream#3]
Can you please give an example with a 3D plot in your documentation? I assume send2d() or the file2d() is the way to go, I guess. But an example would be amazing. I could not find any here - http://www.stahlke.org/dan/gnuplot-iostream. 
Sorry, I found the example code in example-data-2d.cc. But I cnt delete the issue somehow.

**Comment by dstahlke** [comment]
Yes, indeed example-data-2d.cc is the one to look at.  send1d is for 1-dimensional data like curves; send2d is for 2-dimensional data like surfaces or images.  The first takes a list (or list of tuples), the second takes a list of lists or some sort of matrix input.
