### ISSUE TITLE
Define `WIN32_LEAN_AND_MEAN` before including `Windows.h`

### ISSUE THREAD

**Issue by MFHava** [dstahlke/gnuplot-iostream#31]
I had to debug an "interesting" bug in a codebase that was just handed over and is to be ported from Linux to Windows.

Said bug resulted from `interface` being considered a synonym to `struct`. Turns out you include `Windows.h` and indirectly pull in a lot of COM stuff.

Please define `WIN32_LEAN_AND_MEAN` before including that header.

**Comment by dstahlke** [comment]
It looks like Windows.h isn't even needed at all, since _popen comes from stdio.h.  I've pushed this and some other Windows fixes to the master branch.  Let me know if there are further problems.
