### ISSUE TITLE
Deprecated Boost module

### ISSUE THREAD

**Issue by seintcat** [dstahlke/gnuplot-iostream#32]
Check "cmake  --help-policy CMP0167"
The FindBoost module is removed, error return at find_package

**Comment by dstahlke** [comment]
I'm not so familiar with cmake and don't have version 3.30 available.  I gather this is the way to fix it?

```
if(POLICY CMP0167)
cmake_policy(SET CMP0167 NEW)
endif(POLICY CMP0167)
```

I've pushed this change just now.  Please correct me if I'm wrong.

**Comment by seintcat** [comment]
At this case, CMake return error at find_package(also set policy not works).
I'm not used to it either, _"install & link Boost library to my project"_ is all I know.
My purpose about this issue is just notice, so I suggest add troubleshooting tab at readme instead changing CMakeLists.txt.
