### ISSUE TITLE
Gnuplot MFC Visual Studio2017

### ISSUE THREAD

**Issue by lukastenkap** [dstahlke/gnuplot-iostream#4]
Hi,

I´m using gnuplot with VS2017. Everything is fine and working.
But when I try to build an small project with MFC class and a small window,
it is not possible to compile. I get an strange error:
File: libboost_iostreams-vc141-mt-gd-x32-1_66.lib can not be opend.

Can somebody help me?
All boost files are linked correckt (when I start a comand window project, everything is working).
I thing its more an problem of boost than of gnuplot-iostrem but I´m not so familar with this.

Thanks all lot...

**Comment by dstahlke** [comment]
Unfortunately I don't know anything about VS.  Perhaps the compiler 
needs some flag to tell it which directory the boost libraries are in?  
The gcc compiler has a -L flag for this purpose.

- Dan
