### ISSUE TITLE
Can't rotate or zoom in/out 3D figure

### ISSUE THREAD

**Issue by VincentZhou98** [dstahlke/gnuplot-iostream#7]
This header only library works well for static figure showing, but if I can't do some zooming in/out or rotating operations like what I do in the `gnuplot interactive command line mode`. So how to deal with it?

I'm use gnuplot qt terminal on Mac OS X 11, does it depends on the OS?
@dstahlke

**Comment by dstahlke** [comment]
Can you try the `example-data-2d` that comes with gnuplot-iostream?  It does a 3d surface plot.  With gnuplot 5.2.2 with the qt terminal on Ubuntu 18.04, rotate works.  Zoom causes gnuplot to segfault for me, but you can ask the gnuplot team about that.  Zoom does work on the other examples (e.g. `./example-misc basic`).

In general gnuplot often doesn't allow you to zoom after the command line portion of the program quits, even with the `-persist` option.  You can try sleeping your program or waiting for a keystroke before destroying the `Gnuplot` object.

**Comment by VincentZhou98** [comment]
Thanks for your advice. In my case, `example-data-2d` rotating not works, but I think waiting for a keystroke to exit the program may be a good choose. I try it and it works like a charm.
